; Auto-generated. Do not edit!


(cl:in-package ccms_pro-srv)


;//! \htmlinclude ModuleData-request.msg.html

(cl:defclass <ModuleData-request> (roslisp-msg-protocol:ros-message)
  ((ErrorTypeID
    :reader ErrorTypeID
    :initarg :ErrorTypeID
    :type cl:integer
    :initform 0)
   (powerID
    :reader powerID
    :initarg :powerID
    :type cl:integer
    :initform 0)
   (moduleID
    :reader moduleID
    :initarg :moduleID
    :type cl:integer
    :initform 0)
   (blockID
    :reader blockID
    :initarg :blockID
    :type cl:integer
    :initform 0)
   (StartStamp
    :reader StartStamp
    :initarg :StartStamp
    :type cl:float
    :initform 0.0)
   (EndStamp
    :reader EndStamp
    :initarg :EndStamp
    :type cl:float
    :initform 0.0))
)

(cl:defclass ModuleData-request (<ModuleData-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ModuleData-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ModuleData-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ccms_pro-srv:<ModuleData-request> is deprecated: use ccms_pro-srv:ModuleData-request instead.")))

(cl:ensure-generic-function 'ErrorTypeID-val :lambda-list '(m))
(cl:defmethod ErrorTypeID-val ((m <ModuleData-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:ErrorTypeID-val is deprecated.  Use ccms_pro-srv:ErrorTypeID instead.")
  (ErrorTypeID m))

(cl:ensure-generic-function 'powerID-val :lambda-list '(m))
(cl:defmethod powerID-val ((m <ModuleData-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:powerID-val is deprecated.  Use ccms_pro-srv:powerID instead.")
  (powerID m))

(cl:ensure-generic-function 'moduleID-val :lambda-list '(m))
(cl:defmethod moduleID-val ((m <ModuleData-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:moduleID-val is deprecated.  Use ccms_pro-srv:moduleID instead.")
  (moduleID m))

(cl:ensure-generic-function 'blockID-val :lambda-list '(m))
(cl:defmethod blockID-val ((m <ModuleData-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:blockID-val is deprecated.  Use ccms_pro-srv:blockID instead.")
  (blockID m))

(cl:ensure-generic-function 'StartStamp-val :lambda-list '(m))
(cl:defmethod StartStamp-val ((m <ModuleData-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:StartStamp-val is deprecated.  Use ccms_pro-srv:StartStamp instead.")
  (StartStamp m))

(cl:ensure-generic-function 'EndStamp-val :lambda-list '(m))
(cl:defmethod EndStamp-val ((m <ModuleData-request>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:EndStamp-val is deprecated.  Use ccms_pro-srv:EndStamp instead.")
  (EndStamp m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ModuleData-request>) ostream)
  "Serializes a message object of type '<ModuleData-request>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'ErrorTypeID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'ErrorTypeID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'ErrorTypeID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'ErrorTypeID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'ErrorTypeID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'ErrorTypeID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'ErrorTypeID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'ErrorTypeID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'powerID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'powerID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'powerID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'powerID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'powerID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'powerID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'powerID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'powerID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'moduleID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'moduleID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'moduleID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'moduleID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'moduleID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'moduleID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'moduleID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'moduleID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'blockID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'blockID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'blockID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'blockID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'blockID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'blockID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'blockID)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'blockID)) ostream)
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'StartStamp))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'EndStamp))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ModuleData-request>) istream)
  "Deserializes a message object of type '<ModuleData-request>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'ErrorTypeID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'ErrorTypeID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'ErrorTypeID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'ErrorTypeID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'ErrorTypeID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'ErrorTypeID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'ErrorTypeID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'ErrorTypeID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'powerID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'powerID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'powerID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'powerID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'powerID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'powerID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'powerID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'powerID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'moduleID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'moduleID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'moduleID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'moduleID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'moduleID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'moduleID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'moduleID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'moduleID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'blockID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'blockID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'blockID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'blockID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 32) (cl:slot-value msg 'blockID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 40) (cl:slot-value msg 'blockID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 48) (cl:slot-value msg 'blockID)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 56) (cl:slot-value msg 'blockID)) (cl:read-byte istream))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'StartStamp) (roslisp-utils:decode-double-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'EndStamp) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ModuleData-request>)))
  "Returns string type for a service object of type '<ModuleData-request>"
  "ccms_pro/ModuleDataRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ModuleData-request)))
  "Returns string type for a service object of type 'ModuleData-request"
  "ccms_pro/ModuleDataRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ModuleData-request>)))
  "Returns md5sum for a message object of type '<ModuleData-request>"
  "2168a7456167e874f53072b67d551079")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ModuleData-request)))
  "Returns md5sum for a message object of type 'ModuleData-request"
  "2168a7456167e874f53072b67d551079")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ModuleData-request>)))
  "Returns full string definition for message of type '<ModuleData-request>"
  (cl:format cl:nil "uint64 ErrorTypeID~%uint64 powerID~%uint64 moduleID~%uint64 blockID~%float64 StartStamp~%float64 EndStamp~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ModuleData-request)))
  "Returns full string definition for message of type 'ModuleData-request"
  (cl:format cl:nil "uint64 ErrorTypeID~%uint64 powerID~%uint64 moduleID~%uint64 blockID~%float64 StartStamp~%float64 EndStamp~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ModuleData-request>))
  (cl:+ 0
     8
     8
     8
     8
     8
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ModuleData-request>))
  "Converts a ROS message object to a list"
  (cl:list 'ModuleData-request
    (cl:cons ':ErrorTypeID (ErrorTypeID msg))
    (cl:cons ':powerID (powerID msg))
    (cl:cons ':moduleID (moduleID msg))
    (cl:cons ':blockID (blockID msg))
    (cl:cons ':StartStamp (StartStamp msg))
    (cl:cons ':EndStamp (EndStamp msg))
))
;//! \htmlinclude ModuleData-response.msg.html

(cl:defclass <ModuleData-response> (roslisp-msg-protocol:ros-message)
  ((HEnergy
    :reader HEnergy
    :initarg :HEnergy
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (HModule
    :reader HModule
    :initarg :HModule
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (HBlock
    :reader HBlock
    :initarg :HBlock
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (HModule_Average
    :reader HModule_Average
    :initarg :HModule_Average
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (HError
    :reader HError
    :initarg :HError
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass ModuleData-response (<ModuleData-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ModuleData-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ModuleData-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ccms_pro-srv:<ModuleData-response> is deprecated: use ccms_pro-srv:ModuleData-response instead.")))

(cl:ensure-generic-function 'HEnergy-val :lambda-list '(m))
(cl:defmethod HEnergy-val ((m <ModuleData-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:HEnergy-val is deprecated.  Use ccms_pro-srv:HEnergy instead.")
  (HEnergy m))

(cl:ensure-generic-function 'HModule-val :lambda-list '(m))
(cl:defmethod HModule-val ((m <ModuleData-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:HModule-val is deprecated.  Use ccms_pro-srv:HModule instead.")
  (HModule m))

(cl:ensure-generic-function 'HBlock-val :lambda-list '(m))
(cl:defmethod HBlock-val ((m <ModuleData-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:HBlock-val is deprecated.  Use ccms_pro-srv:HBlock instead.")
  (HBlock m))

(cl:ensure-generic-function 'HModule_Average-val :lambda-list '(m))
(cl:defmethod HModule_Average-val ((m <ModuleData-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:HModule_Average-val is deprecated.  Use ccms_pro-srv:HModule_Average instead.")
  (HModule_Average m))

(cl:ensure-generic-function 'HError-val :lambda-list '(m))
(cl:defmethod HError-val ((m <ModuleData-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ccms_pro-srv:HError-val is deprecated.  Use ccms_pro-srv:HError instead.")
  (HError m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ModuleData-response>) ostream)
  "Serializes a message object of type '<ModuleData-response>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'HEnergy))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'HEnergy))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'HModule))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'HModule))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'HBlock))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'HBlock))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'HModule_Average))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'HModule_Average))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'HError))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'HError))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ModuleData-response>) istream)
  "Deserializes a message object of type '<ModuleData-response>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'HEnergy) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'HEnergy)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'HModule) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'HModule)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'HBlock) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'HBlock)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'HModule_Average) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'HModule_Average)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'HError) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'HError)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ModuleData-response>)))
  "Returns string type for a service object of type '<ModuleData-response>"
  "ccms_pro/ModuleDataResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ModuleData-response)))
  "Returns string type for a service object of type 'ModuleData-response"
  "ccms_pro/ModuleDataResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ModuleData-response>)))
  "Returns md5sum for a message object of type '<ModuleData-response>"
  "2168a7456167e874f53072b67d551079")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ModuleData-response)))
  "Returns md5sum for a message object of type 'ModuleData-response"
  "2168a7456167e874f53072b67d551079")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ModuleData-response>)))
  "Returns full string definition for message of type '<ModuleData-response>"
  (cl:format cl:nil "float64[] HEnergy~%float64[] HModule~%float64[] HBlock~%float64[] HModule_Average~%float64[] HError~%~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ModuleData-response)))
  "Returns full string definition for message of type 'ModuleData-response"
  (cl:format cl:nil "float64[] HEnergy~%float64[] HModule~%float64[] HBlock~%float64[] HModule_Average~%float64[] HError~%~%~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ModuleData-response>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'HEnergy) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'HModule) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'HBlock) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'HModule_Average) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'HError) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ModuleData-response>))
  "Converts a ROS message object to a list"
  (cl:list 'ModuleData-response
    (cl:cons ':HEnergy (HEnergy msg))
    (cl:cons ':HModule (HModule msg))
    (cl:cons ':HBlock (HBlock msg))
    (cl:cons ':HModule_Average (HModule_Average msg))
    (cl:cons ':HError (HError msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'ModuleData)))
  'ModuleData-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'ModuleData)))
  'ModuleData-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ModuleData)))
  "Returns string type for a service object of type '<ModuleData>"
  "ccms_pro/ModuleData")