# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ccms_pro/HistoryMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class HistoryMsg(genpy.Message):
  _md5sum = "96fa6e4eb46c88db4088ee987f3ac04d"
  _type = "ccms_pro/HistoryMsg"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint64 Error_Type_Number
uint64 Power_Number
uint64 Module_Number
uint64 Block_Number
uint64 StartTime
uint64 EndTime
"""
  __slots__ = ['Error_Type_Number','Power_Number','Module_Number','Block_Number','StartTime','EndTime']
  _slot_types = ['uint64','uint64','uint64','uint64','uint64','uint64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       Error_Type_Number,Power_Number,Module_Number,Block_Number,StartTime,EndTime

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HistoryMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.Error_Type_Number is None:
        self.Error_Type_Number = 0
      if self.Power_Number is None:
        self.Power_Number = 0
      if self.Module_Number is None:
        self.Module_Number = 0
      if self.Block_Number is None:
        self.Block_Number = 0
      if self.StartTime is None:
        self.StartTime = 0
      if self.EndTime is None:
        self.EndTime = 0
    else:
      self.Error_Type_Number = 0
      self.Power_Number = 0
      self.Module_Number = 0
      self.Block_Number = 0
      self.StartTime = 0
      self.EndTime = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6Q().pack(_x.Error_Type_Number, _x.Power_Number, _x.Module_Number, _x.Block_Number, _x.StartTime, _x.EndTime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.Error_Type_Number, _x.Power_Number, _x.Module_Number, _x.Block_Number, _x.StartTime, _x.EndTime,) = _get_struct_6Q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6Q().pack(_x.Error_Type_Number, _x.Power_Number, _x.Module_Number, _x.Block_Number, _x.StartTime, _x.EndTime))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 48
      (_x.Error_Type_Number, _x.Power_Number, _x.Module_Number, _x.Block_Number, _x.StartTime, _x.EndTime,) = _get_struct_6Q().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6Q = None
def _get_struct_6Q():
    global _struct_6Q
    if _struct_6Q is None:
        _struct_6Q = struct.Struct("<6Q")
    return _struct_6Q
