(cl:in-package ccms_pro-msg)
(cl:export '(ID-VAL
          ID
          STAMP-VAL
          STAMP
          BALANCED_DATA_NUMBER-VAL
          BALANCED_DATA_NUMBER
          MODULES_ABOVE_THRESHOLD_VOLTAGE-VAL
          MODULES_ABOVE_THRESHOLD_VOLTAGE
          MODUEL_AVERAGE_VOLTAGE-VAL
          MODUEL_AVERAGE_VOLTAGE
          MODULE_VOLTAGE_THRESHOLD-VAL
          MODULE_VOLTAGE_THRESHOLD
          MINIMUM_MODULE_VOLTAGE-VAL
          MINIMUM_MODULE_VOLTAGE
))