(cl:in-package ccms_pro-msg)
(cl:export '(ID-VAL
          ID
          STAMP-VAL
          STAMP
          MODULE_VOLTAGE-VAL
          MODULE_VOLTAGE
          MODULE_CAPACITANCE_TEMPERATURE-VAL
          MODULE_CAPACITANCE_TEMPERATURE
          MODULE_BOARD_TEMPERATURE-VAL
          MODULE_BOARD_TEMPERATURE
          MODULE_VOLTAGE_OVERVOLTAGE_ABNORMAL-VAL
          MODULE_VOLTAGE_OVERVOLTAGE_ABNORMAL
          MODULE_CAPACITY_ABNORMAL-VAL
          MODULE_CAPACITY_ABNORMAL
          OTHER_DATA-VAL
          OTHER_DATA
          MODULE_VOLTAGE_OVERVOLTAGE_WARMING-VAL
          MODULE_VOLTAGE_OVERVOLTAGE_WARMING
          MODULE_OVERVOLT_ABNORMAL-VAL
          MODULE_OVERVOLT_ABNORMAL
          MODULE_CAPACITY_ABNORMAL-VAL
          MODULE_CAPACITY_ABNORMAL
          OTHER_DATA_BIT-VAL
          OTHER_DATA_BIT
          MODULE_OVERVOLT_WARMING-VAL
          MODULE_OVERVOLT_WARMING
))