(cl:defpackage ccms_pro-msg
  (:use )
  (:export
   "<BALANCERESULT>"
   "BALANCERESULT"
   "<BATTERYRESULT>"
   "BATTERYRESULT"
   "<BLOCKRESULT>"
   "BLOCKRESULT"
   "<CALCRESULT>"
   "CALCRESULT"
   "<HISTORYMSG>"
   "HISTORYMSG"
   "<MODULERESULT>"
   "MODULERESULT"
   "<UNPACKINGCANDATA1>"
   "UNPACKINGCANDATA1"
   "<UNPACKINGCANDATA2>"
   "UNPACKINGCANDATA2"
   "<UNPACKINGCANDATA3>"
   "UNPACKINGCANDATA3"
   "<UNPACKINGCANDATA4>"
   "UNPACKINGCANDATA4"
   "<UNPACKINGCANDATA5>"
   "UNPACKINGCANDATA5"
   "<UNPACKINGCANDATA6>"
   "UNPACKINGCANDATA6"
  ))

