// Generated by gencpp from file ccms_pro/BalanceResult.msg
// DO NOT EDIT!


#ifndef CCMS_PRO_MESSAGE_BALANCERESULT_H
#define CCMS_PRO_MESSAGE_BALANCERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ccms_pro
{
template <class ContainerAllocator>
struct BalanceResult_
{
  typedef BalanceResult_<ContainerAllocator> Type;

  BalanceResult_()
    : balancestate(0)
    , modID(0)
    , stamp()  {
    }
  BalanceResult_(const ContainerAllocator& _alloc)
    : balancestate(0)
    , modID(0)
    , stamp()  {
  (void)_alloc;
    }



   typedef int16_t _balancestate_type;
  _balancestate_type balancestate;

   typedef int16_t _modID_type;
  _modID_type modID;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::ccms_pro::BalanceResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ccms_pro::BalanceResult_<ContainerAllocator> const> ConstPtr;

}; // struct BalanceResult_

typedef ::ccms_pro::BalanceResult_<std::allocator<void> > BalanceResult;

typedef boost::shared_ptr< ::ccms_pro::BalanceResult > BalanceResultPtr;
typedef boost::shared_ptr< ::ccms_pro::BalanceResult const> BalanceResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ccms_pro::BalanceResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ccms_pro::BalanceResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ccms_pro

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ccms_pro': ['/home/ubuntu/ccms/catkin_ws/src/ccms_pro/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ccms_pro::BalanceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ccms_pro::BalanceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccms_pro::BalanceResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccms_pro::BalanceResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccms_pro::BalanceResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccms_pro::BalanceResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ccms_pro::BalanceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4d0a672bc2e43f660b2b92e9da0e2b66";
  }

  static const char* value(const ::ccms_pro::BalanceResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4d0a672bc2e43f66ULL;
  static const uint64_t static_value2 = 0x0b2b92e9da0e2b66ULL;
};

template<class ContainerAllocator>
struct DataType< ::ccms_pro::BalanceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccms_pro/BalanceResult";
  }

  static const char* value(const ::ccms_pro::BalanceResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ccms_pro::BalanceResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 balancestate\n\
int16 modID\n\
time stamp\n\
";
  }

  static const char* value(const ::ccms_pro::BalanceResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ccms_pro::BalanceResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.balancestate);
      stream.next(m.modID);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BalanceResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ccms_pro::BalanceResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ccms_pro::BalanceResult_<ContainerAllocator>& v)
  {
    s << indent << "balancestate: ";
    Printer<int16_t>::stream(s, indent + "  ", v.balancestate);
    s << indent << "modID: ";
    Printer<int16_t>::stream(s, indent + "  ", v.modID);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CCMS_PRO_MESSAGE_BALANCERESULT_H
