// Generated by gencpp from file ccms_pro/BlockResult.msg
// DO NOT EDIT!


#ifndef CCMS_PRO_MESSAGE_BLOCKRESULT_H
#define CCMS_PRO_MESSAGE_BLOCKRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ccms_pro
{
template <class ContainerAllocator>
struct BlockResult_
{
  typedef BlockResult_<ContainerAllocator> Type;

  BlockResult_()
    : modID(0)
    , blockhealths()
    , stamp()  {
    }
  BlockResult_(const ContainerAllocator& _alloc)
    : modID(0)
    , blockhealths(_alloc)
    , stamp()  {
  (void)_alloc;
    }



   typedef int16_t _modID_type;
  _modID_type modID;

   typedef std::vector<uint16_t, typename ContainerAllocator::template rebind<uint16_t>::other >  _blockhealths_type;
  _blockhealths_type blockhealths;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::ccms_pro::BlockResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ccms_pro::BlockResult_<ContainerAllocator> const> ConstPtr;

}; // struct BlockResult_

typedef ::ccms_pro::BlockResult_<std::allocator<void> > BlockResult;

typedef boost::shared_ptr< ::ccms_pro::BlockResult > BlockResultPtr;
typedef boost::shared_ptr< ::ccms_pro::BlockResult const> BlockResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ccms_pro::BlockResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ccms_pro::BlockResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ccms_pro

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ccms_pro': ['/home/ubuntu/ccms/catkin_ws/src/ccms_pro/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ccms_pro::BlockResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ccms_pro::BlockResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccms_pro::BlockResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccms_pro::BlockResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccms_pro::BlockResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccms_pro::BlockResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ccms_pro::BlockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "19c5aed4873df3f3779e740af6923032";
  }

  static const char* value(const ::ccms_pro::BlockResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x19c5aed4873df3f3ULL;
  static const uint64_t static_value2 = 0x779e740af6923032ULL;
};

template<class ContainerAllocator>
struct DataType< ::ccms_pro::BlockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccms_pro/BlockResult";
  }

  static const char* value(const ::ccms_pro::BlockResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ccms_pro::BlockResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 modID\n\
uint16[] blockhealths \n\
time stamp\n\
";
  }

  static const char* value(const ::ccms_pro::BlockResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ccms_pro::BlockResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.modID);
      stream.next(m.blockhealths);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BlockResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ccms_pro::BlockResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ccms_pro::BlockResult_<ContainerAllocator>& v)
  {
    s << indent << "modID: ";
    Printer<int16_t>::stream(s, indent + "  ", v.modID);
    s << indent << "blockhealths[]" << std::endl;
    for (size_t i = 0; i < v.blockhealths.size(); ++i)
    {
      s << indent << "  blockhealths[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.blockhealths[i]);
    }
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CCMS_PRO_MESSAGE_BLOCKRESULT_H
