// Generated by gencpp from file ccms_pro/CalcResult.msg
// DO NOT EDIT!


#ifndef CCMS_PRO_MESSAGE_CALCRESULT_H
#define CCMS_PRO_MESSAGE_CALCRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ccms_pro
{
template <class ContainerAllocator>
struct CalcResult_
{
  typedef CalcResult_<ContainerAllocator> Type;

  CalcResult_()
    : Rresult()
    , Cresult()
    , stamp()  {
    }
  CalcResult_(const ContainerAllocator& _alloc)
    : Rresult(_alloc)
    , Cresult(_alloc)
    , stamp()  {
  (void)_alloc;
    }



   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _Rresult_type;
  _Rresult_type Rresult;

   typedef std::vector<uint64_t, typename ContainerAllocator::template rebind<uint64_t>::other >  _Cresult_type;
  _Cresult_type Cresult;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;





  typedef boost::shared_ptr< ::ccms_pro::CalcResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ccms_pro::CalcResult_<ContainerAllocator> const> ConstPtr;

}; // struct CalcResult_

typedef ::ccms_pro::CalcResult_<std::allocator<void> > CalcResult;

typedef boost::shared_ptr< ::ccms_pro::CalcResult > CalcResultPtr;
typedef boost::shared_ptr< ::ccms_pro::CalcResult const> CalcResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ccms_pro::CalcResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ccms_pro::CalcResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ccms_pro

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ccms_pro': ['/home/ubuntu/ccms/catkin_ws/src/ccms_pro/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ccms_pro::CalcResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ccms_pro::CalcResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccms_pro::CalcResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccms_pro::CalcResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccms_pro::CalcResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccms_pro::CalcResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ccms_pro::CalcResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "70e22a0b756eec76246b47243b5ea1f7";
  }

  static const char* value(const ::ccms_pro::CalcResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x70e22a0b756eec76ULL;
  static const uint64_t static_value2 = 0x246b47243b5ea1f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ccms_pro::CalcResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccms_pro/CalcResult";
  }

  static const char* value(const ::ccms_pro::CalcResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ccms_pro::CalcResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64[] Rresult\n\
uint64[] Cresult\n\
time stamp\n\
\n\
";
  }

  static const char* value(const ::ccms_pro::CalcResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ccms_pro::CalcResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Rresult);
      stream.next(m.Cresult);
      stream.next(m.stamp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CalcResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ccms_pro::CalcResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ccms_pro::CalcResult_<ContainerAllocator>& v)
  {
    s << indent << "Rresult[]" << std::endl;
    for (size_t i = 0; i < v.Rresult.size(); ++i)
    {
      s << indent << "  Rresult[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.Rresult[i]);
    }
    s << indent << "Cresult[]" << std::endl;
    for (size_t i = 0; i < v.Cresult.size(); ++i)
    {
      s << indent << "  Cresult[" << i << "]: ";
      Printer<uint64_t>::stream(s, indent + "  ", v.Cresult[i]);
    }
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CCMS_PRO_MESSAGE_CALCRESULT_H
