// Generated by gencpp from file ccms_pro/HistoryMsg.msg
// DO NOT EDIT!


#ifndef CCMS_PRO_MESSAGE_HISTORYMSG_H
#define CCMS_PRO_MESSAGE_HISTORYMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ccms_pro
{
template <class ContainerAllocator>
struct HistoryMsg_
{
  typedef HistoryMsg_<ContainerAllocator> Type;

  HistoryMsg_()
    : Error_Type_Number(0)
    , Power_Number(0)
    , Module_Number(0)
    , Block_Number(0)
    , StartTime(0)
    , EndTime(0)  {
    }
  HistoryMsg_(const ContainerAllocator& _alloc)
    : Error_Type_Number(0)
    , Power_Number(0)
    , Module_Number(0)
    , Block_Number(0)
    , StartTime(0)
    , EndTime(0)  {
  (void)_alloc;
    }



   typedef uint64_t _Error_Type_Number_type;
  _Error_Type_Number_type Error_Type_Number;

   typedef uint64_t _Power_Number_type;
  _Power_Number_type Power_Number;

   typedef uint64_t _Module_Number_type;
  _Module_Number_type Module_Number;

   typedef uint64_t _Block_Number_type;
  _Block_Number_type Block_Number;

   typedef uint64_t _StartTime_type;
  _StartTime_type StartTime;

   typedef uint64_t _EndTime_type;
  _EndTime_type EndTime;





  typedef boost::shared_ptr< ::ccms_pro::HistoryMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ccms_pro::HistoryMsg_<ContainerAllocator> const> ConstPtr;

}; // struct HistoryMsg_

typedef ::ccms_pro::HistoryMsg_<std::allocator<void> > HistoryMsg;

typedef boost::shared_ptr< ::ccms_pro::HistoryMsg > HistoryMsgPtr;
typedef boost::shared_ptr< ::ccms_pro::HistoryMsg const> HistoryMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ccms_pro::HistoryMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ccms_pro::HistoryMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ccms_pro

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ccms_pro': ['/home/ubuntu/ccms/catkin_ws/src/ccms_pro/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ccms_pro::HistoryMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ccms_pro::HistoryMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccms_pro::HistoryMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ccms_pro::HistoryMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccms_pro::HistoryMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ccms_pro::HistoryMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ccms_pro::HistoryMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "96fa6e4eb46c88db4088ee987f3ac04d";
  }

  static const char* value(const ::ccms_pro::HistoryMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x96fa6e4eb46c88dbULL;
  static const uint64_t static_value2 = 0x4088ee987f3ac04dULL;
};

template<class ContainerAllocator>
struct DataType< ::ccms_pro::HistoryMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccms_pro/HistoryMsg";
  }

  static const char* value(const ::ccms_pro::HistoryMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ccms_pro::HistoryMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 Error_Type_Number\n\
uint64 Power_Number\n\
uint64 Module_Number\n\
uint64 Block_Number\n\
uint64 StartTime\n\
uint64 EndTime\n\
";
  }

  static const char* value(const ::ccms_pro::HistoryMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ccms_pro::HistoryMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Error_Type_Number);
      stream.next(m.Power_Number);
      stream.next(m.Module_Number);
      stream.next(m.Block_Number);
      stream.next(m.StartTime);
      stream.next(m.EndTime);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HistoryMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ccms_pro::HistoryMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ccms_pro::HistoryMsg_<ContainerAllocator>& v)
  {
    s << indent << "Error_Type_Number: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.Error_Type_Number);
    s << indent << "Power_Number: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.Power_Number);
    s << indent << "Module_Number: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.Module_Number);
    s << indent << "Block_Number: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.Block_Number);
    s << indent << "StartTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.StartTime);
    s << indent << "EndTime: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.EndTime);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CCMS_PRO_MESSAGE_HISTORYMSG_H
